### ISSUE TITLE
[Feature request] Stop using `dart:mirrors` to deduce Command metadata

### ISSUE THREAD

**Issue by abitofevrything** [nyxx-discord/nyxx_commands#11]
**Is your feature request related to a problem? Please describe.**
Currently, code using `nyxx_commands` cannot be compiled as `dart:mirrors` is used to determine metadata about commands, including argument types, annotations but also to assemble converters.

**Describe the solution you'd like**
Stop using `dart:mirrors` and migrate to a compile-friendly solution.

Possible options include:
- `package:build`
- Macros, see dart-lang/language#1482

**Comment by abitofevrything** [comment]
Some existing code will have to be converter to type variables instead of `Type` variables (the language feature vs the type) to perform superclass checking without mirrors. Most notably, assembled converter creation and storage of command argument types will have to be converted to type variables.

A `TypeHolder<T>` class could be added to store command arguments instead of `Type` variables, and a type argument on the `converterFor` method on `CommandsPlugin` can be added to specify the target type instead of the existing function parameter.

Other code, such as the extraction of `@Description`, `@Name`, `@Choices` or `@UseConverter` annotations would have to be done at compile-time, using the aforementioned build package or macros. A new parameter would probably be added to the `Command` constructor to allow passing this data as const variables instead of by converters.

The extraction of command callback parameter types could be done either at compile time or at runtime, although runtime would allow for more flexibility. There is a potential issue with the fact that the number of parameters could theoretically be any arbitrary size, but this can be resolved by adding a maximum number of command arguments - probably 25 to comply with existing Discord limitations.

All of these changes can theoretically be made non-breaking, giving users time to migrate their code until the next major version of `nyxx_commands` would be released, which would remove all deprecated functions.

**Comment by abitofevrything** [comment]
Fixing this issue would probably also allow Flutter and JS runtimes to be used with nyxx_commands.

**Comment by l7ssha** [comment]
> Fixing this issue would probably also allow Flutter and JS runtimes to be used with nyxx_commands.

JS runtime wont happen anyway because we have strong dependency on `dart:io` in nyxx and `nyxx_interactions` and it wont change anytime soon. But flutter could work for sure

**Comment by abitofevrything** [comment]
It would probably be beneficial to keep `mirrors` support but have it locked behind a conditional import for two reasons:
- `mirrors` is quicker to use and offers a faster development cycle;
- `mirrors` allows you to extract metadata from dart objects no matter where they are declared in the code, which is not possible with macros or `build` packages:
```dart
Future<void> run(Context context, @Name('test') String input) {
  // Some code...
}

commands.registerChild(Command(
  'test',
  'A test command',
  run,
));
```
In this case, `mirrors` would be able to extract the metadata on the `input` parameter whereas macros or `build` would struggle. In fact, in certain cases it would be impossible to extract the metadata.

To discuss: should the `mirrors`-based implementation perform the same as compileable options, or should it work universally at the cost of being inconsistent with compiled versions?

**Comment by abitofevrything** [comment]
Due to the limitations of the current Dart runtime type system, the feature set available in compiled `nyxx_commands` would be significantly reduced and probably not worth the performance boost. This issue will be closed, but might be reopened in the future if Dart adds better support for runtime types.
