### ISSUE TITLE
deps: analyzer version

### ISSUE THREAD

**Issue by tomassasovsky** [nyxx-discord/nyxx_commands#98]
The analyzer version is too old, so it becomes an issue when dealing with other dependencies which maintain it updated.
![image](https://user-images.githubusercontent.com/63405252/204409747-7cde4b41-06a1-4d4f-8c26-f99f37cb981e.png)

**Comment by abitofevrything** [comment]
Hi! This has been fixed in the latest prerelease version 5.0.0-dev.1 - can you try that and let me know if it works?

**Comment by tomassasovsky** [comment]
It works! thank you!
